version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue"
  ]
  environment = [
    "nodejs",
    "jquery",
    "browser",
    "vitest"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[code_formatters]]
name = "autopep8"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "prettier"